import type { Declaration } from '../src/Components/Declaration-Card/Declaration_Card';
import type { Employee } from '../src/Components/Employee_Table';

export const registeredEmployees: Employee[] = [
    {
        fullName: 'Carlos Antonio Diaz',
        employeeType: 'MILITARY',
        grossSalary: 82000,
        tin: 'TIN456789123',
        faydaId: 'FYD003',
        pensionPercent: 40,
        monthly_contribution: 32800,
    },
    {
        fullName: 'Carlos Antonio Diaz',
        employeeType: 'MILITARY',
        grossSalary: 82000,
        tin: 'TIN456789123',
        faydaId: 'FYD003',
        pensionPercent: 40,
        monthly_contribution: 32800,
    },
    {
        fullName: 'Carlos Antonio Diaz',
        employeeType: 'MILITARY',
        grossSalary: 82000,
        tin: 'TIN456789123',
        faydaId: 'FYD003',
        pensionPercent: 40,
        monthly_contribution: 32800,
    },
    {
        fullName: 'Carlos Antonio Diaz',
        employeeType: 'MILITARY',
        grossSalary: 82000,
        tin: 'TIN456789123',
        faydaId: 'FYD003',
        pensionPercent: 40,
        monthly_contribution: 32800,
    },
    {
        fullName: 'Carlos Antonio Diaz',
        employeeType: 'MILITARY',
        grossSalary: 82000,
        tin: 'TIN456789123',
        faydaId: 'FYD003',
        pensionPercent: 40,
        monthly_contribution: 32800,
    },
    {
        fullName: 'Diana Rose Wilson',
        employeeType: 'PUBLIC',
        grossSalary: 78000,
        tin: 'TIN321654987',
        faydaId: 'FYD005',
        pensionPercent: 18,
        monthly_contribution: 14040,
    },
    {
        fullName: 'Edward Thompson',
        employeeType: 'POLICE',
        grossSalary: 71000,
        tin: 'TIN654987321',
        faydaId: 'FYD006',
        pensionPercent: 40,
        monthly_contribution: 28400,
    },
    {
        fullName: 'Fatima Al Hassan',
        employeeType: 'MILITARY',
        grossSalary: 85000,
        tin: 'TIN147258369',
        faydaId: 'FYD007',
        pensionPercent: 40,
        monthly_contribution: 34000,
    },
    {
        fullName: 'George Martinez',
        employeeType: 'PRIVATE',
        grossSalary: 92000,
        tin: 'TIN369258147',
        faydaId: 'FYD008',
        pensionPercent: 18,
        monthly_contribution: 16560,
    },
    {
        fullName: 'Hannah Grace Lee',
        employeeType: 'PUBLIC',
        grossSalary: 67000,
        tin: 'TIN258147369',
        faydaId: 'FYD009',
        pensionPercent: 18,
        monthly_contribution: 12060,
    },
    {
        fullName: 'Ibrahim Ahmed',
        employeeType: 'POLICE',
        grossSalary: 73000,
        tin: 'TIN741852963',
        faydaId: 'FYD010',
        pensionPercent: 40,
        monthly_contribution: 29200,
    },
    {
        fullName: 'Julia Ann Roberts',
        employeeType: 'PRIVATE',
        grossSalary: 89000,
        tin: 'TIN963852741',
        faydaId: 'FYD011',
        pensionPercent: 18,
        monthly_contribution: 16020,
    },
];

export const unregisteredEmployees: Employee[] = [
    {
        fullName: 'Sarah Johnson',
        employeeType: 'PRIVATE',
        grossSalary: 68000,
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 12240,
    },
    {
        fullName: 'Sarah Johnson',
        employeeType: 'PRIVATE',
        grossSalary: 68000,
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 12240,
    },
    {
        fullName: 'Sarah Johnson',
        employeeType: 'PRIVATE',
        grossSalary: 68000,
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 12240,
    },
    {
        fullName: 'Sarah Johnson',
        employeeType: 'PRIVATE',
        grossSalary: 68000,
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 12240,
    },
    {
        fullName: 'Sarah Johnson',
        employeeType: 'PRIVATE',
        grossSalary: 68000,
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 12240,
    },
    {
        fullName: 'Michael James Brown',
        employeeType: 'PUBLIC',
        grossSalary: 72000,
        tin: 'TIN789123456',
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 12960,
    },
    {
        fullName: 'Lisa Marie Davis',
        employeeType: 'PRIVATE',
        grossSalary: 65000,
        faydaId: 'FYD012',
        pensionPercent: 18,
        monthly_contribution: 11700,
    },
    {
        fullName: 'Robert Garcia',
        employeeType: 'PUBLIC',
        grossSalary: 70000,
        tin: 'TIN456123789',
        faydaId: 'FYD013',
        pensionPercent: 18,
        monthly_contribution: 12600,
    },
    {
        fullName: 'Amanda Sue Miller',
        employeeType: 'PRIVATE',
        grossSalary: 74000,
        faydaId: 'FYD004',
        pensionPercent: 18,
        monthly_contribution: 13320,
    },
    {
        fullName: 'David Rodriguez',
        employeeType: 'PUBLIC',
        grossSalary: 69000,
        tin: 'TIN789456123',
        faydaId: 'FYD014',
        pensionPercent: 18,
        monthly_contribution: 12420,
    },
    {
        fullName: 'Jennifer Lynn Taylor',
        employeeType: 'PRIVATE',
        grossSalary: 76000,
        faydaId: 'FYD015',
        pensionPercent: 18,
        monthly_contribution: 13680,
    },
];

export const mockDeclarations: Declaration[] = [
    {
        id: 1,
        month: 'January',
        year: '2023',
        status: 'unpaid',
        registeredCount: 19,
        unregisteredCount: 4,
        totalAmount: 83467,
    },
    {
        id: 2,
        month: 'December',
        year: '2024',
        status: 'paid',
        registeredCount: 19,
        unregisteredCount: 10,
        totalAmount: 129224,
    },
    {
        id: 3,
        month: 'September',
        year: '2023',
        status: 'unpaid',
        registeredCount: 13,
        unregisteredCount: 1,
        totalAmount: 57358,
    },
    {
        id: 4,
        month: 'August',
        year: '2025',
        status: 'unpaid',
        registeredCount: 15,
        unregisteredCount: 10,
        totalAmount: 100000,
    },
    {
        id: 5,
        month: 'August',
        year: '2022',
        status: 'paid',
        registeredCount: 30,
        unregisteredCount: 5,
        totalAmount: 163345,
    },
    {
        id: 6,
        month: 'August',
        year: '2025',
        status: 'paid',
        registeredCount: 7,
        unregisteredCount: 4,
        totalAmount: 43164,
    },
    {
        id: 7,
        month: 'October',
        year: '2022',
        status: 'unpaid',
        registeredCount: 18,
        unregisteredCount: 10,
        totalAmount: 96880,
    },
    {
        id: 8,
        month: 'January',
        year: '2023',
        status: 'paid',
        registeredCount: 11,
        unregisteredCount: 9,
        totalAmount: 69680,
    },
    {
        id: 9,
        month: 'March',
        year: '2023',
        status: 'unpaid',
        registeredCount: 6,
        unregisteredCount: 0,
        totalAmount: 19164,
    },
    {
        id: 10,
        month: 'July',
        year: '2024',
        status: 'paid',
        registeredCount: 7,
        unregisteredCount: 4,
        totalAmount: 49148,
    },
    // ...and 40 more entries like these
];